#pragma once

#define QUICK_TAP_TERM 0
#define QUICK_TAP_TERM_PER_KEY
#define HRM_QUICK_TAP_TERM 200
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define TAPPING_TERM 250
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define FLOW_TAP_TERM 150
#define SPECULATIVE_HOLD
#define SPECULATIVE_HOLD_FLOW_TERM FLOW_TAP_TERM
#define OLED_TIMEOUT 0
#define COMBO_TERM 300
#define LAYER_STATE_8BIT

// Split keyboard configuration
#define EE_HANDS
#define SPLIT_USB_TIMEOUT 1000
#define I2C1_CLOCK_SPEED 400000
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_WPM_ENABLE
#define SPLIT_TRANSACTION_IDS_USER USER_SYNC_CAPS_WORD
